## **Logistic Regression**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as stats
import math

In [ ]:
from sklearn.datasets import make_classification

In [ ]:
X,y = make_classification(n_features=4,n_classes=2)

In [ ]:
print(X)

[[ 5.96494582e-01  8.54844005e-01  8.91485419e-01  2.67613118e-01]
 [-1.22048124e+00  3.12642702e-01 -1.20651961e+00  3.40669953e-01]
 [ 9.78648836e-01 -8.48756793e-01  7.88319020e-01 -5.30824029e-01]
 [-1.12485600e+00 -1.24753889e+00 -1.57196429e+00 -3.47622769e-01]
 [ 1.65548006e-01  1.59362623e+00  6.53686860e-01  6.58623657e-01]
 [ 1.39154164e+00 -3.66747598e-01  1.37254242e+00 -3.92848791e-01]
 [-1.55981547e+00 -8.27245795e-02 -1.68643055e+00  2.27607293e-01]
 [-1.83320444e+00  8.69849688e-01 -1.69234888e+00  6.84132643e-01]
 [ 6.55726410e-01  9.33175800e-01  9.78046681e-01  2.91363442e-01]
 [-1.36894074e+00  1.52519353e+00 -1.00148267e+00  8.88113814e-01]
 [ 4.80434655e+00 -3.16821205e+00  4.16905399e+00 -2.17574139e+00]
 [-1.31324570e+00  1.46783642e+00 -9.59331300e-01  8.54003816e-01]
 [-1.36234709e+00  8.17922123e-01 -1.20630386e+00  5.82295785e-01]
 [ 6.33719382e-01 -6.46168115e-01  4.81550192e-01 -3.85332223e-01]
 [ 8.26648647e-01 -7.72142444e-01  6.49342960e-01 -4.72164463e

In [ ]:
print(X.shape)

(100, 4)


In [ ]:
X_df= pd.DataFrame(X,columns=['feature_1','feature_2','feature_3','feature_4'])

In [ ]:
y_df = pd.DataFrame(y,columns=['target'])

In [ ]:
df = pd.concat([X_df,y_df],axis=1)

In [ ]:
print(df)

    feature_1  feature_2  feature_3  feature_4  target
0    0.596495   0.854844   0.891485   0.267613       1
1   -1.220481   0.312643  -1.206520   0.340670       1
2    0.978649  -0.848757   0.788319  -0.530824       0
3   -1.124856  -1.247539  -1.571964  -0.347623       0
4    0.165548   1.593626   0.653687   0.658624       1
..        ...        ...        ...        ...     ...
95   2.831355  -1.986695   2.421144  -1.333745       0
96  -1.053835   0.399999  -1.002828   0.350180       1
97  -0.304568   2.550589   0.439512   1.150241       1
98   2.934308  -2.041034   2.514542  -1.374531       0
99   1.037716  -0.884474   0.840544  -0.556180       0

[100 rows x 5 columns]


**split dataset**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_df,y_df,test_size=0.1,random_state=41) 

**standardize data**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
data = scaler.fit_transform(df)

In [ ]:
df

feature_1  feature_2  feature_3  feature_4  target
0    0.596495   0.854844   0.891485   0.267613       1
1   -1.220481   0.312643  -1.206520   0.340670       1
2    0.978649  -0.848757   0.788319  -0.530824       0
3   -1.124856  -1.247539  -1.571964  -0.347623       0
4    0.165548   1.593626   0.653687   0.658624       1
..        ...        ...        ...        ...     ...
95   2.831355  -1.986695   2.421144  -1.333745       0
96  -1.053835   0.399999  -1.002828   0.350180       1
97  -0.304568   2.550589   0.439512   1.150241       1
98   2.934308  -2.041034   2.514542  -1.374531       0
99   1.037716  -0.884474   0.840544  -0.556180       0

[100 rows x 5 columns]

In [ ]:
data

array([[ 0.50932317,  0.61904928,  0.73978173,  0.32943439,  1.        ],
       [-0.85594944,  0.18996926, -0.88305194,  0.43754803,  1.        ],
       [ 0.79647324, -0.72912355,  0.6599812 , -0.8521381 , -1.        ],
       [-0.7840968 , -1.0447064 , -1.16572807, -0.5810265 , -1.        ],
       [ 0.18551063,  1.20369689,  0.55584151,  0.90807391,  1.        ],
       [ 1.1067202 , -0.34767756,  1.11188546, -0.64795453,  1.        ],
       [-1.11092461, -0.12291122, -1.25426918,  0.2702315 , -1.        ],
       [-1.31634863,  0.63092428, -1.25884709,  0.94582356, -1.        ],
       [ 0.55382986,  0.68103845,  0.80673797,  0.36458146,  1.        ],
       [-0.96750166,  1.14954154, -0.72445325,  1.24768644,  1.        ],
       [ 3.67109612, -2.56466307,  3.27502286, -3.2863799 , -1.        ],
       [-0.9256525 ,  1.10415103, -0.69184863,  1.19720853,  1.        ],
       [-0.9625472 ,  0.58983054, -0.88288506,  0.79511961,  1.        ],
       [ 0.53729382, -0.56880163,  0.4

**functions for logistic regression**

In [ ]:
def initalize(self,X):
  weights = np.zero((X.shape[1]+1,1))
  X = np.c_[np.ones((X.shape[0],1)),X]
  return weights,X

In [ ]:
def sigmoid(self,z):
  sig = 1/1+math.e**(-z)
  return sig

In [ ]:
def cost(self,theta):
  z = np.dot(X,theta)
  cost0 = y.T.dot(math.log(self.sigmoid(z)))
  cost1 = (1-y).T.dot(math.log(1-self.sigmoid(z)))

  cost = -((cost1+cost0))/len(y)
  return cost

In [ ]:
def fit(self,X,y,alpha = 0.001,itr = 100):
  para , X = self.initalize(X)
  cost_list = np.zero(itr)
  for i in range(itr):
    para  = para-alpha*np.dot(X.T,self.sigmoid(np.dot(X,para) - np.reshape(y,(len (y),1))))
    cost_list[i] = cost(para)
    self.para = para
    return cost_list

In [ ]:
def predict(self,X):
  Z = np.dot(self.initialize(X)[1],self.weights)
  lis = []
  for i in self.sigmoid(Z):
    if (i>0.5):
      lis.append(1)
    else:
      lis.append(0)
    return lis 

In [ ]:
def f1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [ ]:
class LogisticRegression():
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
print("Accuracy:",accuracy_score(y_test,y_test_pred))

Accuracy: 0.8


# Airlines 

Training Dataset

In [ ]:
df_train=pd.read_csv("train.csv")

In [ ]:
df_train

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0                0   70172    Male     Loyal Customer   13  Personal Travel   
1                1    5047    Male  disloyal Customer   25  Business travel   
2                2  110028  Female     Loyal Customer   26  Business travel   
3                3   24026  Female     Loyal Customer   25  Business travel   
4                4  119299    Male     Loyal Customer   61  Business travel   
...            ...     ...     ...                ...  ...              ...   
103899      103899   94171  Female  disloyal Customer   23  Business travel   
103900      103900   73097    Male     Loyal Customer   49  Business travel   
103901      103901   68825    Male  disloyal Customer   30  Business travel   
103902      103902   54173  Female  disloyal Customer   22  Business travel   
103903      103903   62567    Male     Loyal Customer   27  Business travel   

           Class  Flight Distance  Inflight wifi service  \
0       Eco Plus              460                      3   
1       Business              235                      3   
2       Business             1142                      2   
3       Business              562                      2   
4       Business              214                      3   
...          ...              ...                    ...   
103899       Eco              192                      2   
103900  Business             2347                      4   
103901  Business             1995                      1   
103902       Eco             1000                      1   
103903  Business             1723                      1   

        Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                       4  ...                       5   
1                                       2  ...                       1   
2                                       2  ...                       5   
3                                       5  ...                       2   
4                                       3  ...                       3   
...                                   ...  ...                     ...   
103899                                  1  ...                       2   
103900                                  4  ...                       5   
103901                                  1  ...                       4   
103902                                  1  ...                       1   
103903                                  3  ...                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      4                 3                 4                4   
1                      1                 5                 3                1   
2                      4                 3                 4                4   
3                      2                 5                 3                1   
4                      3                 4                 4                3   
...                  ...               ...               ...              ...   
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 1                 4                4   

        Inflight service  Cleanliness  Departure Delay in Minutes  \
0                      5            5                          25   
1                      4            1                           1   
2                      4            5                           0   
3                      4            2                          11   
4                      3            3                           0   
...                  ...          ...                         

In [ ]:
df_train=df_train.drop(['Unnamed: 0'],axis=1)
df_train=df_train.drop(['id'],axis=1)

In [ ]:
df_train.isnull().sum()

Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [ ]:
c=df_train["Arrival Delay in Minutes"].mean()
df_train["Arrival Delay in Minutes"].fillna(c, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
clms=['Gender', 'Customer Type', 'Type of Travel', 'Class', "satisfaction"]
for x in clms:
    df_train[x]=lbl.fit_transform(df_train[x])

In [ ]:
X_train = df_train.iloc[:, :-1].values
Y_train= df_train.iloc[:, -1].values

Testing Dataset

In [ ]:
df_test=pd.read_csv("test.csv")

In [ ]:
df_test

Unnamed: 0     id  Gender      Customer Type  Age   Type of Travel  \
0               0  19556  Female     Loyal Customer   52  Business travel   
1               1  90035  Female     Loyal Customer   36  Business travel   
2               2  12360    Male  disloyal Customer   20  Business travel   
3               3  77959    Male     Loyal Customer   44  Business travel   
4               4  36875  Female     Loyal Customer   49  Business travel   
...           ...    ...     ...                ...  ...              ...   
25971       25971  78463    Male  disloyal Customer   34  Business travel   
25972       25972  71167    Male     Loyal Customer   23  Business travel   
25973       25973  37675  Female     Loyal Customer   17  Personal Travel   
25974       25974  90086    Male     Loyal Customer   14  Business travel   
25975       25975  34799  Female     Loyal Customer   42  Personal Travel   

          Class  Flight Distance  Inflight wifi service  \
0           Eco              160                      5   
1      Business             2863                      1   
2           Eco              192                      2   
3      Business             3377                      0   
4           Eco             1182                      2   
...         ...              ...                    ...   
25971  Business              526                      3   
25972  Business              646                      4   
25973       Eco              828                      2   
25974  Business             1127                      3   
25975       Eco              264                      2   

       Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                      4  ...                       5   
1                                      1  ...                       4   
2                                      0  ...                       2   
3                                      0  ...                       1   
4                                      3  ...                       2   
...                                  ...  ...                     ...   
25971                                  3  ...                       4   
25972                                  4  ...                       4   
25973                                  5  ...                       2   
25974                                  3  ...                       4   
25975                                  5  ...                       1   

       On-board service  Leg room service  Baggage handling  Checkin service  \
0                     5                 5                 5                2   
1                     4                 4                 4                3   
2                     4                 1                 3                2   
3                     1                 1                 1                3   
4                     2                 2                 2                4   
...                 ...               ...               ...              ...   
25971                 3                 2                 4                4   
25972                 4                 5                 5                5   
25973                 4                 3                 4                5   
25974                 3                 2                 5                4   
25975                 1                 2                 1                1   

       Inflight service  Cleanliness  Departure Delay in Minutes  \
0                     5            5                          50   
1                     4            5                           0   
2                     2            2                           0   
3                     1            4                           0   
4                     2            4                           0   
...                 ...          ...                         ...   
25971                 5            4                       

In [ ]:
df_test=df_test.drop(['Unnamed: 0'],axis=1)
df_test=df_test.drop(['id'],axis=1)

In [ ]:
df_test.isnull().sum()

Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [ ]:
c=df_test["Arrival Delay in Minutes"].mean()
df_test["Arrival Delay in Minutes"].fillna(c, inplace=True)

In [ ]:
df_test.isnull().sum()

Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [ ]:
lbl1=LabelEncoder()
clms=['Gender', 'Customer Type', 'Type of Travel', 'Class', "satisfaction"]
for x in clms:
    df_test[x]=lbl1.fit_transform(df_test[x])

In [ ]:
X_test = df_test.iloc[:, :-1].values
Y_test = df_test.iloc[:, -1].values

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,Y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.8624884508777333


In [ ]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression(solver="lbfgs",penalty="l2",max_iter=3000)
model1.fit(X_train,Y_train)

LogisticRegression(max_iter=3000)

In [ ]:
y_pred1=model1.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_pred1)
print(f"Accuracy: {accuracy}")

Accuracy: 0.8707653218355405
