In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as stats
import math

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_features=4,n_classes=2)

In [4]:
print(X)

[[-1.10497098e+00  4.96546687e-01 -1.14401851e+00 -9.99253230e-01]
 [-1.27925671e+00  1.93025517e+00  6.90010495e-01 -5.50001277e-01]
 [-4.79813021e-01  4.69318989e-01 -1.19697738e-01 -3.20313923e-01]
 [ 1.51627279e-01 -1.75247888e-01 -2.20937680e-03  8.91627142e-02]
 [ 2.04893317e+00 -1.84596260e+00  7.46207916e-01  1.43864217e+00]
 [ 1.29419290e+00 -7.01511693e-01  1.16167384e+00  1.11667234e+00]
 [-2.95082924e+00  1.98133637e+00 -2.08114337e+00 -2.37510206e+00]
 [-2.31508400e+00  1.43307755e+00 -1.81318295e+00 -1.91774515e+00]
 [ 1.99518294e+00 -1.87782462e+00  6.07303291e-01  1.36495380e+00]
 [-2.24613731e+00  1.86658547e+00 -1.05144099e+00 -1.64742337e+00]
 [ 1.26573425e+00 -5.95068359e-01  1.27140571e+00  1.13286951e+00]
 [-1.00222985e+00 -1.69197575e-01 -1.95850234e+00 -1.18375085e+00]
 [-1.14210739e-01  1.44354415e+00  1.95096905e+00  5.20070427e-01]
 [-8.15590041e-01  1.53398220e+00  8.90773364e-01 -2.14831930e-01]
 [-1.35714726e-01 -9.32620992e-02 -3.69766201e-01 -1.91793820e

In [5]:
print(X.shape)

(100, 4)


In [6]:
X_df= pd.DataFrame(X,columns=['feature_1','feature_2','feature_3','feature_4'])

In [7]:
y_df = pd.DataFrame(y,columns=['target'])

In [8]:
df = pd.concat([X_df,y_df],axis=1)

In [9]:
print(df)

    feature_1  feature_2  feature_3  feature_4  target
0   -1.104971   0.496547  -1.144019  -0.999253       1
1   -1.279257   1.930255   0.690010  -0.550001       1
2   -0.479813   0.469319  -0.119698  -0.320314       0
3    0.151627  -0.175248  -0.002209   0.089163       1
4    2.048933  -1.845963   0.746208   1.438642       1
..        ...        ...        ...        ...     ...
95   0.058627  -0.898258  -1.235198  -0.337373       0
96  -0.089127  -0.751506  -1.268744  -0.435012       0
97  -1.988008   1.594332  -1.016430  -1.483953       0
98   1.094995  -0.567948   1.020905   0.956255       1
99   0.612999  -0.929200  -0.336964   0.261647       0

[100 rows x 5 columns]


**split dataset**

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(X_df,y_df,test_size=0.1,random_state=41) 

**standardize data**

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
data = scaler.fit_transform(df)

In [15]:
df

feature_1  feature_2  feature_3  feature_4  target
0   -1.104971   0.496547  -1.144019  -0.999253       1
1   -1.279257   1.930255   0.690010  -0.550001       1
2   -0.479813   0.469319  -0.119698  -0.320314       0
3    0.151627  -0.175248  -0.002209   0.089163       1
4    2.048933  -1.845963   0.746208   1.438642       1
..        ...        ...        ...        ...     ...
95   0.058627  -0.898258  -1.235198  -0.337373       0
96  -0.089127  -0.751506  -1.268744  -0.435012       0
97  -1.988008   1.594332  -1.016430  -1.483953       0
98   1.094995  -0.567948   1.020905   0.956255       1
99   0.612999  -0.929200  -0.336964   0.261647       0

[100 rows x 5 columns]

In [16]:
data

array([[-0.87190163,  0.47022911, -0.85682226, -0.96376927,  1.        ],
       [-1.01067452,  1.68025586,  0.65854335, -0.51328037,  1.        ],
       [-0.37412719,  0.44724937, -0.0104777 , -0.2829606 , -1.        ],
       [ 0.12864949, -0.09675464,  0.086597  ,  0.12764347,  1.        ],
       [ 1.63935628, -1.50681081,  0.70497645,  1.48083851,  1.        ],
       [ 1.0384035 , -0.54091277,  1.04825497,  1.1579822 ,  1.        ],
       [-2.34164387,  1.72336757, -1.63112125, -2.3434063 , -1.        ],
       [-1.83543944,  1.26064599, -1.40971908, -1.88479012, -1.        ],
       [ 1.59655832, -1.53370185,  0.59020657,  1.40694726,  1.        ],
       [-1.78054148,  1.62651966, -0.78033014, -1.61372405, -1.        ],
       [ 1.01574365, -0.45107632,  1.13892088,  1.17422396,  1.        ],
       [-0.79009525, -0.09164827, -1.52978915, -1.14877488, -1.        ],
       [-0.08302081,  1.26947964,  1.70040978,  0.55973762,  1.        ],
       [-0.64148557,  1.34580789,  0.8

**intialize parameter**

In [22]:
def initalize(self,x):
  weights = np.zero((x.shape(x)[1]+1,1))
  x = np.c_[np.ones((x.shape(x)[0],1)),x]
  return weights,x

In [20]:
def sigmoid(self,z):
  sig = 1/1+e**(-z)
  return sig

In [25]:
def cost(theta):
  z = dot(x,theta)
  cost0 = y.T.dot(math.log(self.sigmoid(z)))
  cost1 = (1-y).T.dot(math.log(1-self.sigmoid(z)))

  cost = -((cost1+cost0))/len(y)
  return cost

In [27]:
def fit(self,x,y,alpha=0.001,itr=100):
  para,x = self.initialize(x)
  cost_list = np.zero(itr)
  for i in range(itr):
    para = para-alpha*np.dot(x.T,self.sigmod(np.dot(x,para)-np.reshape(y,(len(y),1))))
    cost_list[i] = cost(para)
    self.para = para
    return cost_list

In [28]:
def Predict(self,x):
  z = np.dot(self.initialize(x)[1],self.weights)
  lis = []
  for i in self.sigmoid(z):
    if(i>0.5):
      lis.append(1)
    else:
      lis.append(0)
    return lis

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
clf = LogisticRegression(random_state=0)
clf.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [33]:
Y_pred = clf.predict(x_test)

In [36]:
clf = clf.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
clf = clf.fit(x_test,y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [39]:
y_train_pred = clf.predict(x_train)
y_test_pred = clf.predict(x_test)

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [44]:
clf.score(X,y)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


0.85

**accuracy score**

In [29]:
from sklearn.metrics import accuracy_score
