In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_features=4,n_classes=2)

In [4]:
print(X)

[[-1.12281071 -2.0133352   1.61846034 -0.25738488]
 [-0.84486337 -0.58181349  0.60311311  0.42278383]
 [-2.60468439  0.45264855  0.37957466  2.78744351]
 [-1.27888568  0.62748516 -0.08058328  1.63633186]
 [ 2.56698844 -2.32615591  0.86441785 -3.98912826]
 [-0.94419491 -0.44304972  0.53754853  0.60935285]
 [-1.32886195 -0.34641703  0.5739846   1.04068671]
 [-0.5187578   1.22499117 -0.67198508  1.30486784]
 [ 1.51067276 -1.46056376  0.56906575 -2.40812975]
 [ 1.64000095  1.38006182 -1.33586486 -0.65507799]
 [-0.76914456  0.09698479  0.13624821  0.79888066]
 [-0.80108852  1.02475952 -0.46661664  1.44231581]
 [-0.78375249 -0.0636453   0.2458653   0.70671919]
 [-0.31708084  0.94400726 -0.53936326  0.92656706]
 [-0.23024731 -1.87887396  1.29763117 -1.02127435]
 [-1.73076632  1.31707216 -0.41726975  2.52360313]
 [ 2.20957845 -1.95566036  0.71335268 -3.40291225]
 [ 1.07818836 -0.08761718 -0.22283482 -1.08794001]
 [-1.48677429 -2.24579337  1.8662997  -0.06323805]
 [ 1.0380144  -0.23324344 -0.11

In [5]:
print(X.shape)

(100, 4)


In [6]:
X_df= pd.DataFrame(X,columns=['feature_1','feature_2','feature_3','feature_4'])

In [7]:
y_df = pd.DataFrame(y,columns=['target'])

In [8]:
df = pd.concat([X_df,y_df],axis=1)

In [9]:
print(df)

    feature_1  feature_2  feature_3  feature_4  target
0   -1.122811  -2.013335   1.618460  -0.257385       0
1   -0.844863  -0.581813   0.603113   0.422784       0
2   -2.604684   0.452649   0.379575   2.787444       1
3   -1.278886   0.627485  -0.080583   1.636332       1
4    2.566988  -2.326156   0.864418  -3.989128       0
..        ...        ...        ...        ...     ...
95  -0.190547   1.605372  -1.007966   1.242600       1
96   0.788948  -1.759136   0.953550  -1.915870       0
97  -0.530749   1.239501  -0.678423   1.325910       1
98  -0.146941  -0.286810   0.227173  -0.049094       0
99  -1.037581  -0.963561   0.904738   0.354705       0

[100 rows x 5 columns]


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(X_df,y_df,test_size=0.1,random_state=41) 

In [12]:
from sklearn.linear_model import LogisticRegression